
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActionResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ActionResult
 * 
 */
export type ActionResultModel = runtime.Types.Result.DefaultSelection<Prisma.$ActionResultPayload>

export type AggregateActionResult = {
  _count: ActionResultCountAggregateOutputType | null
  _min: ActionResultMinAggregateOutputType | null
  _max: ActionResultMaxAggregateOutputType | null
}

export type ActionResultMinAggregateOutputType = {
  id: string | null
  actionId: string | null
  success: boolean | null
  message: string | null
  executedAt: Date | null
  createdAt: Date | null
}

export type ActionResultMaxAggregateOutputType = {
  id: string | null
  actionId: string | null
  success: boolean | null
  message: string | null
  executedAt: Date | null
  createdAt: Date | null
}

export type ActionResultCountAggregateOutputType = {
  id: number
  actionId: number
  success: number
  message: number
  executedAt: number
  data: number
  createdAt: number
  _all: number
}


export type ActionResultMinAggregateInputType = {
  id?: true
  actionId?: true
  success?: true
  message?: true
  executedAt?: true
  createdAt?: true
}

export type ActionResultMaxAggregateInputType = {
  id?: true
  actionId?: true
  success?: true
  message?: true
  executedAt?: true
  createdAt?: true
}

export type ActionResultCountAggregateInputType = {
  id?: true
  actionId?: true
  success?: true
  message?: true
  executedAt?: true
  data?: true
  createdAt?: true
  _all?: true
}

export type ActionResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionResult to aggregate.
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionResults to fetch.
   */
  orderBy?: Prisma.ActionResultOrderByWithRelationInput | Prisma.ActionResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActionResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActionResults
  **/
  _count?: true | ActionResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActionResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActionResultMaxAggregateInputType
}

export type GetActionResultAggregateType<T extends ActionResultAggregateArgs> = {
      [P in keyof T & keyof AggregateActionResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActionResult[P]>
    : Prisma.GetScalarType<T[P], AggregateActionResult[P]>
}




export type ActionResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionResultWhereInput
  orderBy?: Prisma.ActionResultOrderByWithAggregationInput | Prisma.ActionResultOrderByWithAggregationInput[]
  by: Prisma.ActionResultScalarFieldEnum[] | Prisma.ActionResultScalarFieldEnum
  having?: Prisma.ActionResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActionResultCountAggregateInputType | true
  _min?: ActionResultMinAggregateInputType
  _max?: ActionResultMaxAggregateInputType
}

export type ActionResultGroupByOutputType = {
  id: string
  actionId: string
  success: boolean
  message: string
  executedAt: Date
  data: runtime.JsonValue | null
  createdAt: Date
  _count: ActionResultCountAggregateOutputType | null
  _min: ActionResultMinAggregateOutputType | null
  _max: ActionResultMaxAggregateOutputType | null
}

type GetActionResultGroupByPayload<T extends ActionResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActionResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActionResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActionResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActionResultGroupByOutputType[P]>
      }
    >
  >



export type ActionResultWhereInput = {
  AND?: Prisma.ActionResultWhereInput | Prisma.ActionResultWhereInput[]
  OR?: Prisma.ActionResultWhereInput[]
  NOT?: Prisma.ActionResultWhereInput | Prisma.ActionResultWhereInput[]
  id?: Prisma.StringFilter<"ActionResult"> | string
  actionId?: Prisma.StringFilter<"ActionResult"> | string
  success?: Prisma.BoolFilter<"ActionResult"> | boolean
  message?: Prisma.StringFilter<"ActionResult"> | string
  executedAt?: Prisma.DateTimeFilter<"ActionResult"> | Date | string
  data?: Prisma.JsonNullableFilter<"ActionResult">
  createdAt?: Prisma.DateTimeFilter<"ActionResult"> | Date | string
  action?: Prisma.XOR<Prisma.ActionScalarRelationFilter, Prisma.ActionWhereInput>
}

export type ActionResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  success?: Prisma.SortOrder
  message?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  data?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  action?: Prisma.ActionOrderByWithRelationInput
}

export type ActionResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  actionId?: string
  AND?: Prisma.ActionResultWhereInput | Prisma.ActionResultWhereInput[]
  OR?: Prisma.ActionResultWhereInput[]
  NOT?: Prisma.ActionResultWhereInput | Prisma.ActionResultWhereInput[]
  success?: Prisma.BoolFilter<"ActionResult"> | boolean
  message?: Prisma.StringFilter<"ActionResult"> | string
  executedAt?: Prisma.DateTimeFilter<"ActionResult"> | Date | string
  data?: Prisma.JsonNullableFilter<"ActionResult">
  createdAt?: Prisma.DateTimeFilter<"ActionResult"> | Date | string
  action?: Prisma.XOR<Prisma.ActionScalarRelationFilter, Prisma.ActionWhereInput>
}, "id" | "actionId">

export type ActionResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  success?: Prisma.SortOrder
  message?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  data?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ActionResultCountOrderByAggregateInput
  _max?: Prisma.ActionResultMaxOrderByAggregateInput
  _min?: Prisma.ActionResultMinOrderByAggregateInput
}

export type ActionResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActionResultScalarWhereWithAggregatesInput | Prisma.ActionResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActionResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActionResultScalarWhereWithAggregatesInput | Prisma.ActionResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ActionResult"> | string
  actionId?: Prisma.StringWithAggregatesFilter<"ActionResult"> | string
  success?: Prisma.BoolWithAggregatesFilter<"ActionResult"> | boolean
  message?: Prisma.StringWithAggregatesFilter<"ActionResult"> | string
  executedAt?: Prisma.DateTimeWithAggregatesFilter<"ActionResult"> | Date | string
  data?: Prisma.JsonNullableWithAggregatesFilter<"ActionResult">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ActionResult"> | Date | string
}

export type ActionResultCreateInput = {
  id?: string
  success: boolean
  message: string
  executedAt?: Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  action: Prisma.ActionCreateNestedOneWithoutResultInput
}

export type ActionResultUncheckedCreateInput = {
  id?: string
  actionId: string
  success: boolean
  message: string
  executedAt?: Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ActionResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  action?: Prisma.ActionUpdateOneRequiredWithoutResultNestedInput
}

export type ActionResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionResultCreateManyInput = {
  id?: string
  actionId: string
  success: boolean
  message: string
  executedAt?: Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ActionResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionResultNullableScalarRelationFilter = {
  is?: Prisma.ActionResultWhereInput | null
  isNot?: Prisma.ActionResultWhereInput | null
}

export type ActionResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  success?: Prisma.SortOrder
  message?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActionResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  success?: Prisma.SortOrder
  message?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActionResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  success?: Prisma.SortOrder
  message?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActionResultCreateNestedOneWithoutActionInput = {
  create?: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
  connectOrCreate?: Prisma.ActionResultCreateOrConnectWithoutActionInput
  connect?: Prisma.ActionResultWhereUniqueInput
}

export type ActionResultUncheckedCreateNestedOneWithoutActionInput = {
  create?: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
  connectOrCreate?: Prisma.ActionResultCreateOrConnectWithoutActionInput
  connect?: Prisma.ActionResultWhereUniqueInput
}

export type ActionResultUpdateOneWithoutActionNestedInput = {
  create?: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
  connectOrCreate?: Prisma.ActionResultCreateOrConnectWithoutActionInput
  upsert?: Prisma.ActionResultUpsertWithoutActionInput
  disconnect?: Prisma.ActionResultWhereInput | boolean
  delete?: Prisma.ActionResultWhereInput | boolean
  connect?: Prisma.ActionResultWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ActionResultUpdateToOneWithWhereWithoutActionInput, Prisma.ActionResultUpdateWithoutActionInput>, Prisma.ActionResultUncheckedUpdateWithoutActionInput>
}

export type ActionResultUncheckedUpdateOneWithoutActionNestedInput = {
  create?: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
  connectOrCreate?: Prisma.ActionResultCreateOrConnectWithoutActionInput
  upsert?: Prisma.ActionResultUpsertWithoutActionInput
  disconnect?: Prisma.ActionResultWhereInput | boolean
  delete?: Prisma.ActionResultWhereInput | boolean
  connect?: Prisma.ActionResultWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ActionResultUpdateToOneWithWhereWithoutActionInput, Prisma.ActionResultUpdateWithoutActionInput>, Prisma.ActionResultUncheckedUpdateWithoutActionInput>
}

export type ActionResultCreateWithoutActionInput = {
  id?: string
  success: boolean
  message: string
  executedAt?: Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ActionResultUncheckedCreateWithoutActionInput = {
  id?: string
  success: boolean
  message: string
  executedAt?: Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ActionResultCreateOrConnectWithoutActionInput = {
  where: Prisma.ActionResultWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
}

export type ActionResultUpsertWithoutActionInput = {
  update: Prisma.XOR<Prisma.ActionResultUpdateWithoutActionInput, Prisma.ActionResultUncheckedUpdateWithoutActionInput>
  create: Prisma.XOR<Prisma.ActionResultCreateWithoutActionInput, Prisma.ActionResultUncheckedCreateWithoutActionInput>
  where?: Prisma.ActionResultWhereInput
}

export type ActionResultUpdateToOneWithWhereWithoutActionInput = {
  where?: Prisma.ActionResultWhereInput
  data: Prisma.XOR<Prisma.ActionResultUpdateWithoutActionInput, Prisma.ActionResultUncheckedUpdateWithoutActionInput>
}

export type ActionResultUpdateWithoutActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionResultUncheckedUpdateWithoutActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  message?: Prisma.StringFieldUpdateOperationsInput | string
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  data?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ActionResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  success?: boolean
  message?: boolean
  executedAt?: boolean
  data?: boolean
  createdAt?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionResult"]>

export type ActionResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  success?: boolean
  message?: boolean
  executedAt?: boolean
  data?: boolean
  createdAt?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionResult"]>

export type ActionResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  success?: boolean
  message?: boolean
  executedAt?: boolean
  data?: boolean
  createdAt?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionResult"]>

export type ActionResultSelectScalar = {
  id?: boolean
  actionId?: boolean
  success?: boolean
  message?: boolean
  executedAt?: boolean
  data?: boolean
  createdAt?: boolean
}

export type ActionResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "actionId" | "success" | "message" | "executedAt" | "data" | "createdAt", ExtArgs["result"]["actionResult"]>
export type ActionResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}
export type ActionResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}
export type ActionResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
}

export type $ActionResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActionResult"
  objects: {
    action: Prisma.$ActionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    actionId: string
    success: boolean
    message: string
    executedAt: Date
    data: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["actionResult"]>
  composites: {}
}

export type ActionResultGetPayload<S extends boolean | null | undefined | ActionResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActionResultPayload, S>

export type ActionResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActionResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActionResultCountAggregateInputType | true
  }

export interface ActionResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActionResult'], meta: { name: 'ActionResult' } }
  /**
   * Find zero or one ActionResult that matches the filter.
   * @param {ActionResultFindUniqueArgs} args - Arguments to find a ActionResult
   * @example
   * // Get one ActionResult
   * const actionResult = await prisma.actionResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActionResultFindUniqueArgs>(args: Prisma.SelectSubset<T, ActionResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActionResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActionResultFindUniqueOrThrowArgs} args - Arguments to find a ActionResult
   * @example
   * // Get one ActionResult
   * const actionResult = await prisma.actionResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActionResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActionResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultFindFirstArgs} args - Arguments to find a ActionResult
   * @example
   * // Get one ActionResult
   * const actionResult = await prisma.actionResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActionResultFindFirstArgs>(args?: Prisma.SelectSubset<T, ActionResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultFindFirstOrThrowArgs} args - Arguments to find a ActionResult
   * @example
   * // Get one ActionResult
   * const actionResult = await prisma.actionResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActionResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActionResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActionResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActionResults
   * const actionResults = await prisma.actionResult.findMany()
   * 
   * // Get first 10 ActionResults
   * const actionResults = await prisma.actionResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const actionResultWithIdOnly = await prisma.actionResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActionResultFindManyArgs>(args?: Prisma.SelectSubset<T, ActionResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActionResult.
   * @param {ActionResultCreateArgs} args - Arguments to create a ActionResult.
   * @example
   * // Create one ActionResult
   * const ActionResult = await prisma.actionResult.create({
   *   data: {
   *     // ... data to create a ActionResult
   *   }
   * })
   * 
   */
  create<T extends ActionResultCreateArgs>(args: Prisma.SelectSubset<T, ActionResultCreateArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActionResults.
   * @param {ActionResultCreateManyArgs} args - Arguments to create many ActionResults.
   * @example
   * // Create many ActionResults
   * const actionResult = await prisma.actionResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActionResultCreateManyArgs>(args?: Prisma.SelectSubset<T, ActionResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ActionResults and returns the data saved in the database.
   * @param {ActionResultCreateManyAndReturnArgs} args - Arguments to create many ActionResults.
   * @example
   * // Create many ActionResults
   * const actionResult = await prisma.actionResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ActionResults and only return the `id`
   * const actionResultWithIdOnly = await prisma.actionResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActionResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActionResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ActionResult.
   * @param {ActionResultDeleteArgs} args - Arguments to delete one ActionResult.
   * @example
   * // Delete one ActionResult
   * const ActionResult = await prisma.actionResult.delete({
   *   where: {
   *     // ... filter to delete one ActionResult
   *   }
   * })
   * 
   */
  delete<T extends ActionResultDeleteArgs>(args: Prisma.SelectSubset<T, ActionResultDeleteArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActionResult.
   * @param {ActionResultUpdateArgs} args - Arguments to update one ActionResult.
   * @example
   * // Update one ActionResult
   * const actionResult = await prisma.actionResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActionResultUpdateArgs>(args: Prisma.SelectSubset<T, ActionResultUpdateArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActionResults.
   * @param {ActionResultDeleteManyArgs} args - Arguments to filter ActionResults to delete.
   * @example
   * // Delete a few ActionResults
   * const { count } = await prisma.actionResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActionResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActionResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActionResults
   * const actionResult = await prisma.actionResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActionResultUpdateManyArgs>(args: Prisma.SelectSubset<T, ActionResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionResults and returns the data updated in the database.
   * @param {ActionResultUpdateManyAndReturnArgs} args - Arguments to update many ActionResults.
   * @example
   * // Update many ActionResults
   * const actionResult = await prisma.actionResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ActionResults and only return the `id`
   * const actionResultWithIdOnly = await prisma.actionResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActionResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActionResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ActionResult.
   * @param {ActionResultUpsertArgs} args - Arguments to update or create a ActionResult.
   * @example
   * // Update or create a ActionResult
   * const actionResult = await prisma.actionResult.upsert({
   *   create: {
   *     // ... data to create a ActionResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActionResult we want to update
   *   }
   * })
   */
  upsert<T extends ActionResultUpsertArgs>(args: Prisma.SelectSubset<T, ActionResultUpsertArgs<ExtArgs>>): Prisma.Prisma__ActionResultClient<runtime.Types.Result.GetResult<Prisma.$ActionResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActionResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultCountArgs} args - Arguments to filter ActionResults to count.
   * @example
   * // Count the number of ActionResults
   * const count = await prisma.actionResult.count({
   *   where: {
   *     // ... the filter for the ActionResults we want to count
   *   }
   * })
  **/
  count<T extends ActionResultCountArgs>(
    args?: Prisma.Subset<T, ActionResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActionResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActionResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActionResultAggregateArgs>(args: Prisma.Subset<T, ActionResultAggregateArgs>): Prisma.PrismaPromise<GetActionResultAggregateType<T>>

  /**
   * Group by ActionResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActionResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActionResultGroupByArgs['orderBy'] }
      : { orderBy?: ActionResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActionResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActionResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActionResult model
 */
readonly fields: ActionResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActionResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActionResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  action<T extends Prisma.ActionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionDefaultArgs<ExtArgs>>): Prisma.Prisma__ActionClient<runtime.Types.Result.GetResult<Prisma.$ActionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActionResult model
 */
export interface ActionResultFieldRefs {
  readonly id: Prisma.FieldRef<"ActionResult", 'String'>
  readonly actionId: Prisma.FieldRef<"ActionResult", 'String'>
  readonly success: Prisma.FieldRef<"ActionResult", 'Boolean'>
  readonly message: Prisma.FieldRef<"ActionResult", 'String'>
  readonly executedAt: Prisma.FieldRef<"ActionResult", 'DateTime'>
  readonly data: Prisma.FieldRef<"ActionResult", 'Json'>
  readonly createdAt: Prisma.FieldRef<"ActionResult", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ActionResult findUnique
 */
export type ActionResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter, which ActionResult to fetch.
   */
  where: Prisma.ActionResultWhereUniqueInput
}

/**
 * ActionResult findUniqueOrThrow
 */
export type ActionResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter, which ActionResult to fetch.
   */
  where: Prisma.ActionResultWhereUniqueInput
}

/**
 * ActionResult findFirst
 */
export type ActionResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter, which ActionResult to fetch.
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionResults to fetch.
   */
  orderBy?: Prisma.ActionResultOrderByWithRelationInput | Prisma.ActionResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionResults.
   */
  cursor?: Prisma.ActionResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionResults.
   */
  distinct?: Prisma.ActionResultScalarFieldEnum | Prisma.ActionResultScalarFieldEnum[]
}

/**
 * ActionResult findFirstOrThrow
 */
export type ActionResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter, which ActionResult to fetch.
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionResults to fetch.
   */
  orderBy?: Prisma.ActionResultOrderByWithRelationInput | Prisma.ActionResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionResults.
   */
  cursor?: Prisma.ActionResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionResults.
   */
  distinct?: Prisma.ActionResultScalarFieldEnum | Prisma.ActionResultScalarFieldEnum[]
}

/**
 * ActionResult findMany
 */
export type ActionResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter, which ActionResults to fetch.
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionResults to fetch.
   */
  orderBy?: Prisma.ActionResultOrderByWithRelationInput | Prisma.ActionResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActionResults.
   */
  cursor?: Prisma.ActionResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionResults.
   */
  skip?: number
  distinct?: Prisma.ActionResultScalarFieldEnum | Prisma.ActionResultScalarFieldEnum[]
}

/**
 * ActionResult create
 */
export type ActionResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * The data needed to create a ActionResult.
   */
  data: Prisma.XOR<Prisma.ActionResultCreateInput, Prisma.ActionResultUncheckedCreateInput>
}

/**
 * ActionResult createMany
 */
export type ActionResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActionResults.
   */
  data: Prisma.ActionResultCreateManyInput | Prisma.ActionResultCreateManyInput[]
}

/**
 * ActionResult createManyAndReturn
 */
export type ActionResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * The data used to create many ActionResults.
   */
  data: Prisma.ActionResultCreateManyInput | Prisma.ActionResultCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ActionResult update
 */
export type ActionResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * The data needed to update a ActionResult.
   */
  data: Prisma.XOR<Prisma.ActionResultUpdateInput, Prisma.ActionResultUncheckedUpdateInput>
  /**
   * Choose, which ActionResult to update.
   */
  where: Prisma.ActionResultWhereUniqueInput
}

/**
 * ActionResult updateMany
 */
export type ActionResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActionResults.
   */
  data: Prisma.XOR<Prisma.ActionResultUpdateManyMutationInput, Prisma.ActionResultUncheckedUpdateManyInput>
  /**
   * Filter which ActionResults to update
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * Limit how many ActionResults to update.
   */
  limit?: number
}

/**
 * ActionResult updateManyAndReturn
 */
export type ActionResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * The data used to update ActionResults.
   */
  data: Prisma.XOR<Prisma.ActionResultUpdateManyMutationInput, Prisma.ActionResultUncheckedUpdateManyInput>
  /**
   * Filter which ActionResults to update
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * Limit how many ActionResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ActionResult upsert
 */
export type ActionResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * The filter to search for the ActionResult to update in case it exists.
   */
  where: Prisma.ActionResultWhereUniqueInput
  /**
   * In case the ActionResult found by the `where` argument doesn't exist, create a new ActionResult with this data.
   */
  create: Prisma.XOR<Prisma.ActionResultCreateInput, Prisma.ActionResultUncheckedCreateInput>
  /**
   * In case the ActionResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActionResultUpdateInput, Prisma.ActionResultUncheckedUpdateInput>
}

/**
 * ActionResult delete
 */
export type ActionResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
  /**
   * Filter which ActionResult to delete.
   */
  where: Prisma.ActionResultWhereUniqueInput
}

/**
 * ActionResult deleteMany
 */
export type ActionResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionResults to delete
   */
  where?: Prisma.ActionResultWhereInput
  /**
   * Limit how many ActionResults to delete.
   */
  limit?: number
}

/**
 * ActionResult without action
 */
export type ActionResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionResult
   */
  select?: Prisma.ActionResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionResult
   */
  omit?: Prisma.ActionResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionResultInclude<ExtArgs> | null
}
