
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ComputerStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ComputerStatus
 * 
 */
export type ComputerStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$ComputerStatusPayload>

export type AggregateComputerStatus = {
  _count: ComputerStatusCountAggregateOutputType | null
  _avg: ComputerStatusAvgAggregateOutputType | null
  _sum: ComputerStatusSumAggregateOutputType | null
  _min: ComputerStatusMinAggregateOutputType | null
  _max: ComputerStatusMaxAggregateOutputType | null
}

export type ComputerStatusAvgAggregateOutputType = {
  cpuUsage: number | null
  memoryUsage: number | null
}

export type ComputerStatusSumAggregateOutputType = {
  cpuUsage: number | null
  memoryUsage: number | null
}

export type ComputerStatusMinAggregateOutputType = {
  id: string | null
  ip: string | null
  uptime: string | null
  cpuUsage: number | null
  memoryUsage: number | null
  isScreenOn: boolean | null
  isKioskMode: boolean | null
  lastHeartbeat: Date | null
  timestamp: Date | null
  updatedAt: Date | null
}

export type ComputerStatusMaxAggregateOutputType = {
  id: string | null
  ip: string | null
  uptime: string | null
  cpuUsage: number | null
  memoryUsage: number | null
  isScreenOn: boolean | null
  isKioskMode: boolean | null
  lastHeartbeat: Date | null
  timestamp: Date | null
  updatedAt: Date | null
}

export type ComputerStatusCountAggregateOutputType = {
  id: number
  ip: number
  uptime: number
  cpuUsage: number
  memoryUsage: number
  isScreenOn: number
  isKioskMode: number
  lastHeartbeat: number
  timestamp: number
  updatedAt: number
  _all: number
}


export type ComputerStatusAvgAggregateInputType = {
  cpuUsage?: true
  memoryUsage?: true
}

export type ComputerStatusSumAggregateInputType = {
  cpuUsage?: true
  memoryUsage?: true
}

export type ComputerStatusMinAggregateInputType = {
  id?: true
  ip?: true
  uptime?: true
  cpuUsage?: true
  memoryUsage?: true
  isScreenOn?: true
  isKioskMode?: true
  lastHeartbeat?: true
  timestamp?: true
  updatedAt?: true
}

export type ComputerStatusMaxAggregateInputType = {
  id?: true
  ip?: true
  uptime?: true
  cpuUsage?: true
  memoryUsage?: true
  isScreenOn?: true
  isKioskMode?: true
  lastHeartbeat?: true
  timestamp?: true
  updatedAt?: true
}

export type ComputerStatusCountAggregateInputType = {
  id?: true
  ip?: true
  uptime?: true
  cpuUsage?: true
  memoryUsage?: true
  isScreenOn?: true
  isKioskMode?: true
  lastHeartbeat?: true
  timestamp?: true
  updatedAt?: true
  _all?: true
}

export type ComputerStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ComputerStatus to aggregate.
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ComputerStatuses to fetch.
   */
  orderBy?: Prisma.ComputerStatusOrderByWithRelationInput | Prisma.ComputerStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ComputerStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ComputerStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ComputerStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ComputerStatuses
  **/
  _count?: true | ComputerStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ComputerStatusAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ComputerStatusSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ComputerStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ComputerStatusMaxAggregateInputType
}

export type GetComputerStatusAggregateType<T extends ComputerStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateComputerStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateComputerStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateComputerStatus[P]>
}




export type ComputerStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ComputerStatusWhereInput
  orderBy?: Prisma.ComputerStatusOrderByWithAggregationInput | Prisma.ComputerStatusOrderByWithAggregationInput[]
  by: Prisma.ComputerStatusScalarFieldEnum[] | Prisma.ComputerStatusScalarFieldEnum
  having?: Prisma.ComputerStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ComputerStatusCountAggregateInputType | true
  _avg?: ComputerStatusAvgAggregateInputType
  _sum?: ComputerStatusSumAggregateInputType
  _min?: ComputerStatusMinAggregateInputType
  _max?: ComputerStatusMaxAggregateInputType
}

export type ComputerStatusGroupByOutputType = {
  id: string
  ip: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn: boolean
  isKioskMode: boolean
  lastHeartbeat: Date
  timestamp: Date
  updatedAt: Date
  _count: ComputerStatusCountAggregateOutputType | null
  _avg: ComputerStatusAvgAggregateOutputType | null
  _sum: ComputerStatusSumAggregateOutputType | null
  _min: ComputerStatusMinAggregateOutputType | null
  _max: ComputerStatusMaxAggregateOutputType | null
}

type GetComputerStatusGroupByPayload<T extends ComputerStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ComputerStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ComputerStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ComputerStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ComputerStatusGroupByOutputType[P]>
      }
    >
  >



export type ComputerStatusWhereInput = {
  AND?: Prisma.ComputerStatusWhereInput | Prisma.ComputerStatusWhereInput[]
  OR?: Prisma.ComputerStatusWhereInput[]
  NOT?: Prisma.ComputerStatusWhereInput | Prisma.ComputerStatusWhereInput[]
  id?: Prisma.StringFilter<"ComputerStatus"> | string
  ip?: Prisma.StringFilter<"ComputerStatus"> | string
  uptime?: Prisma.StringFilter<"ComputerStatus"> | string
  cpuUsage?: Prisma.FloatFilter<"ComputerStatus"> | number
  memoryUsage?: Prisma.FloatFilter<"ComputerStatus"> | number
  isScreenOn?: Prisma.BoolFilter<"ComputerStatus"> | boolean
  isKioskMode?: Prisma.BoolFilter<"ComputerStatus"> | boolean
  lastHeartbeat?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  timestamp?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  server?: Prisma.XOR<Prisma.ServerScalarRelationFilter, Prisma.ServerWhereInput>
}

export type ComputerStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  uptime?: Prisma.SortOrder
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
  isScreenOn?: Prisma.SortOrder
  isKioskMode?: Prisma.SortOrder
  lastHeartbeat?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  server?: Prisma.ServerOrderByWithRelationInput
}

export type ComputerStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  ip?: string
  AND?: Prisma.ComputerStatusWhereInput | Prisma.ComputerStatusWhereInput[]
  OR?: Prisma.ComputerStatusWhereInput[]
  NOT?: Prisma.ComputerStatusWhereInput | Prisma.ComputerStatusWhereInput[]
  uptime?: Prisma.StringFilter<"ComputerStatus"> | string
  cpuUsage?: Prisma.FloatFilter<"ComputerStatus"> | number
  memoryUsage?: Prisma.FloatFilter<"ComputerStatus"> | number
  isScreenOn?: Prisma.BoolFilter<"ComputerStatus"> | boolean
  isKioskMode?: Prisma.BoolFilter<"ComputerStatus"> | boolean
  lastHeartbeat?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  timestamp?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ComputerStatus"> | Date | string
  server?: Prisma.XOR<Prisma.ServerScalarRelationFilter, Prisma.ServerWhereInput>
}, "id" | "ip">

export type ComputerStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  uptime?: Prisma.SortOrder
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
  isScreenOn?: Prisma.SortOrder
  isKioskMode?: Prisma.SortOrder
  lastHeartbeat?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ComputerStatusCountOrderByAggregateInput
  _avg?: Prisma.ComputerStatusAvgOrderByAggregateInput
  _max?: Prisma.ComputerStatusMaxOrderByAggregateInput
  _min?: Prisma.ComputerStatusMinOrderByAggregateInput
  _sum?: Prisma.ComputerStatusSumOrderByAggregateInput
}

export type ComputerStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.ComputerStatusScalarWhereWithAggregatesInput | Prisma.ComputerStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.ComputerStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ComputerStatusScalarWhereWithAggregatesInput | Prisma.ComputerStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ComputerStatus"> | string
  ip?: Prisma.StringWithAggregatesFilter<"ComputerStatus"> | string
  uptime?: Prisma.StringWithAggregatesFilter<"ComputerStatus"> | string
  cpuUsage?: Prisma.FloatWithAggregatesFilter<"ComputerStatus"> | number
  memoryUsage?: Prisma.FloatWithAggregatesFilter<"ComputerStatus"> | number
  isScreenOn?: Prisma.BoolWithAggregatesFilter<"ComputerStatus"> | boolean
  isKioskMode?: Prisma.BoolWithAggregatesFilter<"ComputerStatus"> | boolean
  lastHeartbeat?: Prisma.DateTimeWithAggregatesFilter<"ComputerStatus"> | Date | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"ComputerStatus"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ComputerStatus"> | Date | string
}

export type ComputerStatusCreateInput = {
  id?: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: Date | string
  timestamp?: Date | string
  updatedAt?: Date | string
  server: Prisma.ServerCreateNestedOneWithoutComputerStatusInput
}

export type ComputerStatusUncheckedCreateInput = {
  id?: string
  ip: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: Date | string
  timestamp?: Date | string
  updatedAt?: Date | string
}

export type ComputerStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  server?: Prisma.ServerUpdateOneRequiredWithoutComputerStatusNestedInput
}

export type ComputerStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComputerStatusCreateManyInput = {
  id?: string
  ip: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: Date | string
  timestamp?: Date | string
  updatedAt?: Date | string
}

export type ComputerStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComputerStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComputerStatusNullableScalarRelationFilter = {
  is?: Prisma.ComputerStatusWhereInput | null
  isNot?: Prisma.ComputerStatusWhereInput | null
}

export type ComputerStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  uptime?: Prisma.SortOrder
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
  isScreenOn?: Prisma.SortOrder
  isKioskMode?: Prisma.SortOrder
  lastHeartbeat?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComputerStatusAvgOrderByAggregateInput = {
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
}

export type ComputerStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  uptime?: Prisma.SortOrder
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
  isScreenOn?: Prisma.SortOrder
  isKioskMode?: Prisma.SortOrder
  lastHeartbeat?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComputerStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  uptime?: Prisma.SortOrder
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
  isScreenOn?: Prisma.SortOrder
  isKioskMode?: Prisma.SortOrder
  lastHeartbeat?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComputerStatusSumOrderByAggregateInput = {
  cpuUsage?: Prisma.SortOrder
  memoryUsage?: Prisma.SortOrder
}

export type ComputerStatusCreateNestedOneWithoutServerInput = {
  create?: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
  connectOrCreate?: Prisma.ComputerStatusCreateOrConnectWithoutServerInput
  connect?: Prisma.ComputerStatusWhereUniqueInput
}

export type ComputerStatusUncheckedCreateNestedOneWithoutServerInput = {
  create?: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
  connectOrCreate?: Prisma.ComputerStatusCreateOrConnectWithoutServerInput
  connect?: Prisma.ComputerStatusWhereUniqueInput
}

export type ComputerStatusUpdateOneWithoutServerNestedInput = {
  create?: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
  connectOrCreate?: Prisma.ComputerStatusCreateOrConnectWithoutServerInput
  upsert?: Prisma.ComputerStatusUpsertWithoutServerInput
  disconnect?: Prisma.ComputerStatusWhereInput | boolean
  delete?: Prisma.ComputerStatusWhereInput | boolean
  connect?: Prisma.ComputerStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ComputerStatusUpdateToOneWithWhereWithoutServerInput, Prisma.ComputerStatusUpdateWithoutServerInput>, Prisma.ComputerStatusUncheckedUpdateWithoutServerInput>
}

export type ComputerStatusUncheckedUpdateOneWithoutServerNestedInput = {
  create?: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
  connectOrCreate?: Prisma.ComputerStatusCreateOrConnectWithoutServerInput
  upsert?: Prisma.ComputerStatusUpsertWithoutServerInput
  disconnect?: Prisma.ComputerStatusWhereInput | boolean
  delete?: Prisma.ComputerStatusWhereInput | boolean
  connect?: Prisma.ComputerStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ComputerStatusUpdateToOneWithWhereWithoutServerInput, Prisma.ComputerStatusUpdateWithoutServerInput>, Prisma.ComputerStatusUncheckedUpdateWithoutServerInput>
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ComputerStatusCreateWithoutServerInput = {
  id?: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: Date | string
  timestamp?: Date | string
  updatedAt?: Date | string
}

export type ComputerStatusUncheckedCreateWithoutServerInput = {
  id?: string
  uptime: string
  cpuUsage: number
  memoryUsage: number
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: Date | string
  timestamp?: Date | string
  updatedAt?: Date | string
}

export type ComputerStatusCreateOrConnectWithoutServerInput = {
  where: Prisma.ComputerStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
}

export type ComputerStatusUpsertWithoutServerInput = {
  update: Prisma.XOR<Prisma.ComputerStatusUpdateWithoutServerInput, Prisma.ComputerStatusUncheckedUpdateWithoutServerInput>
  create: Prisma.XOR<Prisma.ComputerStatusCreateWithoutServerInput, Prisma.ComputerStatusUncheckedCreateWithoutServerInput>
  where?: Prisma.ComputerStatusWhereInput
}

export type ComputerStatusUpdateToOneWithWhereWithoutServerInput = {
  where?: Prisma.ComputerStatusWhereInput
  data: Prisma.XOR<Prisma.ComputerStatusUpdateWithoutServerInput, Prisma.ComputerStatusUncheckedUpdateWithoutServerInput>
}

export type ComputerStatusUpdateWithoutServerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComputerStatusUncheckedUpdateWithoutServerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uptime?: Prisma.StringFieldUpdateOperationsInput | string
  cpuUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  memoryUsage?: Prisma.FloatFieldUpdateOperationsInput | number
  isScreenOn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isKioskMode?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastHeartbeat?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ComputerStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip?: boolean
  uptime?: boolean
  cpuUsage?: boolean
  memoryUsage?: boolean
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: boolean
  timestamp?: boolean
  updatedAt?: boolean
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["computerStatus"]>

export type ComputerStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip?: boolean
  uptime?: boolean
  cpuUsage?: boolean
  memoryUsage?: boolean
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: boolean
  timestamp?: boolean
  updatedAt?: boolean
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["computerStatus"]>

export type ComputerStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip?: boolean
  uptime?: boolean
  cpuUsage?: boolean
  memoryUsage?: boolean
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: boolean
  timestamp?: boolean
  updatedAt?: boolean
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["computerStatus"]>

export type ComputerStatusSelectScalar = {
  id?: boolean
  ip?: boolean
  uptime?: boolean
  cpuUsage?: boolean
  memoryUsage?: boolean
  isScreenOn?: boolean
  isKioskMode?: boolean
  lastHeartbeat?: boolean
  timestamp?: boolean
  updatedAt?: boolean
}

export type ComputerStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ip" | "uptime" | "cpuUsage" | "memoryUsage" | "isScreenOn" | "isKioskMode" | "lastHeartbeat" | "timestamp" | "updatedAt", ExtArgs["result"]["computerStatus"]>
export type ComputerStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}
export type ComputerStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}
export type ComputerStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  server?: boolean | Prisma.ServerDefaultArgs<ExtArgs>
}

export type $ComputerStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ComputerStatus"
  objects: {
    server: Prisma.$ServerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ip: string
    uptime: string
    cpuUsage: number
    memoryUsage: number
    isScreenOn: boolean
    isKioskMode: boolean
    lastHeartbeat: Date
    timestamp: Date
    updatedAt: Date
  }, ExtArgs["result"]["computerStatus"]>
  composites: {}
}

export type ComputerStatusGetPayload<S extends boolean | null | undefined | ComputerStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload, S>

export type ComputerStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ComputerStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ComputerStatusCountAggregateInputType | true
  }

export interface ComputerStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ComputerStatus'], meta: { name: 'ComputerStatus' } }
  /**
   * Find zero or one ComputerStatus that matches the filter.
   * @param {ComputerStatusFindUniqueArgs} args - Arguments to find a ComputerStatus
   * @example
   * // Get one ComputerStatus
   * const computerStatus = await prisma.computerStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ComputerStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, ComputerStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ComputerStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ComputerStatusFindUniqueOrThrowArgs} args - Arguments to find a ComputerStatus
   * @example
   * // Get one ComputerStatus
   * const computerStatus = await prisma.computerStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ComputerStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ComputerStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ComputerStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusFindFirstArgs} args - Arguments to find a ComputerStatus
   * @example
   * // Get one ComputerStatus
   * const computerStatus = await prisma.computerStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ComputerStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, ComputerStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ComputerStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusFindFirstOrThrowArgs} args - Arguments to find a ComputerStatus
   * @example
   * // Get one ComputerStatus
   * const computerStatus = await prisma.computerStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ComputerStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ComputerStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ComputerStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ComputerStatuses
   * const computerStatuses = await prisma.computerStatus.findMany()
   * 
   * // Get first 10 ComputerStatuses
   * const computerStatuses = await prisma.computerStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const computerStatusWithIdOnly = await prisma.computerStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ComputerStatusFindManyArgs>(args?: Prisma.SelectSubset<T, ComputerStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ComputerStatus.
   * @param {ComputerStatusCreateArgs} args - Arguments to create a ComputerStatus.
   * @example
   * // Create one ComputerStatus
   * const ComputerStatus = await prisma.computerStatus.create({
   *   data: {
   *     // ... data to create a ComputerStatus
   *   }
   * })
   * 
   */
  create<T extends ComputerStatusCreateArgs>(args: Prisma.SelectSubset<T, ComputerStatusCreateArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ComputerStatuses.
   * @param {ComputerStatusCreateManyArgs} args - Arguments to create many ComputerStatuses.
   * @example
   * // Create many ComputerStatuses
   * const computerStatus = await prisma.computerStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ComputerStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, ComputerStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ComputerStatuses and returns the data saved in the database.
   * @param {ComputerStatusCreateManyAndReturnArgs} args - Arguments to create many ComputerStatuses.
   * @example
   * // Create many ComputerStatuses
   * const computerStatus = await prisma.computerStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ComputerStatuses and only return the `id`
   * const computerStatusWithIdOnly = await prisma.computerStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ComputerStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ComputerStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ComputerStatus.
   * @param {ComputerStatusDeleteArgs} args - Arguments to delete one ComputerStatus.
   * @example
   * // Delete one ComputerStatus
   * const ComputerStatus = await prisma.computerStatus.delete({
   *   where: {
   *     // ... filter to delete one ComputerStatus
   *   }
   * })
   * 
   */
  delete<T extends ComputerStatusDeleteArgs>(args: Prisma.SelectSubset<T, ComputerStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ComputerStatus.
   * @param {ComputerStatusUpdateArgs} args - Arguments to update one ComputerStatus.
   * @example
   * // Update one ComputerStatus
   * const computerStatus = await prisma.computerStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ComputerStatusUpdateArgs>(args: Prisma.SelectSubset<T, ComputerStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ComputerStatuses.
   * @param {ComputerStatusDeleteManyArgs} args - Arguments to filter ComputerStatuses to delete.
   * @example
   * // Delete a few ComputerStatuses
   * const { count } = await prisma.computerStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ComputerStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, ComputerStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ComputerStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ComputerStatuses
   * const computerStatus = await prisma.computerStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ComputerStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, ComputerStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ComputerStatuses and returns the data updated in the database.
   * @param {ComputerStatusUpdateManyAndReturnArgs} args - Arguments to update many ComputerStatuses.
   * @example
   * // Update many ComputerStatuses
   * const computerStatus = await prisma.computerStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ComputerStatuses and only return the `id`
   * const computerStatusWithIdOnly = await prisma.computerStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ComputerStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ComputerStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ComputerStatus.
   * @param {ComputerStatusUpsertArgs} args - Arguments to update or create a ComputerStatus.
   * @example
   * // Update or create a ComputerStatus
   * const computerStatus = await prisma.computerStatus.upsert({
   *   create: {
   *     // ... data to create a ComputerStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ComputerStatus we want to update
   *   }
   * })
   */
  upsert<T extends ComputerStatusUpsertArgs>(args: Prisma.SelectSubset<T, ComputerStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__ComputerStatusClient<runtime.Types.Result.GetResult<Prisma.$ComputerStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ComputerStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusCountArgs} args - Arguments to filter ComputerStatuses to count.
   * @example
   * // Count the number of ComputerStatuses
   * const count = await prisma.computerStatus.count({
   *   where: {
   *     // ... the filter for the ComputerStatuses we want to count
   *   }
   * })
  **/
  count<T extends ComputerStatusCountArgs>(
    args?: Prisma.Subset<T, ComputerStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ComputerStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ComputerStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ComputerStatusAggregateArgs>(args: Prisma.Subset<T, ComputerStatusAggregateArgs>): Prisma.PrismaPromise<GetComputerStatusAggregateType<T>>

  /**
   * Group by ComputerStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComputerStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ComputerStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ComputerStatusGroupByArgs['orderBy'] }
      : { orderBy?: ComputerStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ComputerStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetComputerStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ComputerStatus model
 */
readonly fields: ComputerStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ComputerStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ComputerStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  server<T extends Prisma.ServerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServerDefaultArgs<ExtArgs>>): Prisma.Prisma__ServerClient<runtime.Types.Result.GetResult<Prisma.$ServerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ComputerStatus model
 */
export interface ComputerStatusFieldRefs {
  readonly id: Prisma.FieldRef<"ComputerStatus", 'String'>
  readonly ip: Prisma.FieldRef<"ComputerStatus", 'String'>
  readonly uptime: Prisma.FieldRef<"ComputerStatus", 'String'>
  readonly cpuUsage: Prisma.FieldRef<"ComputerStatus", 'Float'>
  readonly memoryUsage: Prisma.FieldRef<"ComputerStatus", 'Float'>
  readonly isScreenOn: Prisma.FieldRef<"ComputerStatus", 'Boolean'>
  readonly isKioskMode: Prisma.FieldRef<"ComputerStatus", 'Boolean'>
  readonly lastHeartbeat: Prisma.FieldRef<"ComputerStatus", 'DateTime'>
  readonly timestamp: Prisma.FieldRef<"ComputerStatus", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ComputerStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ComputerStatus findUnique
 */
export type ComputerStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter, which ComputerStatus to fetch.
   */
  where: Prisma.ComputerStatusWhereUniqueInput
}

/**
 * ComputerStatus findUniqueOrThrow
 */
export type ComputerStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter, which ComputerStatus to fetch.
   */
  where: Prisma.ComputerStatusWhereUniqueInput
}

/**
 * ComputerStatus findFirst
 */
export type ComputerStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter, which ComputerStatus to fetch.
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ComputerStatuses to fetch.
   */
  orderBy?: Prisma.ComputerStatusOrderByWithRelationInput | Prisma.ComputerStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ComputerStatuses.
   */
  cursor?: Prisma.ComputerStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ComputerStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ComputerStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ComputerStatuses.
   */
  distinct?: Prisma.ComputerStatusScalarFieldEnum | Prisma.ComputerStatusScalarFieldEnum[]
}

/**
 * ComputerStatus findFirstOrThrow
 */
export type ComputerStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter, which ComputerStatus to fetch.
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ComputerStatuses to fetch.
   */
  orderBy?: Prisma.ComputerStatusOrderByWithRelationInput | Prisma.ComputerStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ComputerStatuses.
   */
  cursor?: Prisma.ComputerStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ComputerStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ComputerStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ComputerStatuses.
   */
  distinct?: Prisma.ComputerStatusScalarFieldEnum | Prisma.ComputerStatusScalarFieldEnum[]
}

/**
 * ComputerStatus findMany
 */
export type ComputerStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter, which ComputerStatuses to fetch.
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ComputerStatuses to fetch.
   */
  orderBy?: Prisma.ComputerStatusOrderByWithRelationInput | Prisma.ComputerStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ComputerStatuses.
   */
  cursor?: Prisma.ComputerStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ComputerStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ComputerStatuses.
   */
  skip?: number
  distinct?: Prisma.ComputerStatusScalarFieldEnum | Prisma.ComputerStatusScalarFieldEnum[]
}

/**
 * ComputerStatus create
 */
export type ComputerStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a ComputerStatus.
   */
  data: Prisma.XOR<Prisma.ComputerStatusCreateInput, Prisma.ComputerStatusUncheckedCreateInput>
}

/**
 * ComputerStatus createMany
 */
export type ComputerStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ComputerStatuses.
   */
  data: Prisma.ComputerStatusCreateManyInput | Prisma.ComputerStatusCreateManyInput[]
}

/**
 * ComputerStatus createManyAndReturn
 */
export type ComputerStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * The data used to create many ComputerStatuses.
   */
  data: Prisma.ComputerStatusCreateManyInput | Prisma.ComputerStatusCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ComputerStatus update
 */
export type ComputerStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a ComputerStatus.
   */
  data: Prisma.XOR<Prisma.ComputerStatusUpdateInput, Prisma.ComputerStatusUncheckedUpdateInput>
  /**
   * Choose, which ComputerStatus to update.
   */
  where: Prisma.ComputerStatusWhereUniqueInput
}

/**
 * ComputerStatus updateMany
 */
export type ComputerStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ComputerStatuses.
   */
  data: Prisma.XOR<Prisma.ComputerStatusUpdateManyMutationInput, Prisma.ComputerStatusUncheckedUpdateManyInput>
  /**
   * Filter which ComputerStatuses to update
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * Limit how many ComputerStatuses to update.
   */
  limit?: number
}

/**
 * ComputerStatus updateManyAndReturn
 */
export type ComputerStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * The data used to update ComputerStatuses.
   */
  data: Prisma.XOR<Prisma.ComputerStatusUpdateManyMutationInput, Prisma.ComputerStatusUncheckedUpdateManyInput>
  /**
   * Filter which ComputerStatuses to update
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * Limit how many ComputerStatuses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ComputerStatus upsert
 */
export type ComputerStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the ComputerStatus to update in case it exists.
   */
  where: Prisma.ComputerStatusWhereUniqueInput
  /**
   * In case the ComputerStatus found by the `where` argument doesn't exist, create a new ComputerStatus with this data.
   */
  create: Prisma.XOR<Prisma.ComputerStatusCreateInput, Prisma.ComputerStatusUncheckedCreateInput>
  /**
   * In case the ComputerStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ComputerStatusUpdateInput, Prisma.ComputerStatusUncheckedUpdateInput>
}

/**
 * ComputerStatus delete
 */
export type ComputerStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
  /**
   * Filter which ComputerStatus to delete.
   */
  where: Prisma.ComputerStatusWhereUniqueInput
}

/**
 * ComputerStatus deleteMany
 */
export type ComputerStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ComputerStatuses to delete
   */
  where?: Prisma.ComputerStatusWhereInput
  /**
   * Limit how many ComputerStatuses to delete.
   */
  limit?: number
}

/**
 * ComputerStatus without action
 */
export type ComputerStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComputerStatus
   */
  select?: Prisma.ComputerStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComputerStatus
   */
  omit?: Prisma.ComputerStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComputerStatusInclude<ExtArgs> | null
}
